"""add_missing_browser_session_columns

Revision ID: 0436cd4d4827
Revises: 002
Create Date: 2026-02-10 06:40:18.806750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0436cd4d4827'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('browser_sessions', sa.Column('videos_watched', sa.Integer(), nullable=False))
    op.alter_column('browser_sessions', 'total_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'active_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'background_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'pages_visited',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'videos_started_not_finished',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'shorts_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'total_scroll_pixels',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'thumbnails_hovered',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'thumbnails_clicked',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'page_reloads',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'back_button_presses',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'recommendation_clicks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'autoplay_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'autoplay_cancelled',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'search_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'time_on_home_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'time_on_watch_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'time_on_search_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'time_on_shorts_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'productive_videos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'unproductive_videos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('browser_sessions', 'neutral_videos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('browser_sessions', 'video_count')
    op.drop_column('browser_sessions', 'active_seconds')
    op.drop_column('browser_sessions', 'duration_seconds')
    op.alter_column('daily_stats', 'total_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'active_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'background_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'session_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'avg_session_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'video_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'videos_completed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'videos_abandoned',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'shorts_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'unique_channels',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'search_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'recommendation_clicks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'autoplay_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'autoplay_cancelled',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'total_scroll_pixels',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'avg_scroll_velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('daily_stats', 'thumbnails_hovered',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'thumbnails_clicked',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'page_reloads',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'back_button_presses',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'tab_switches',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'productive_videos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'unproductive_videos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'neutral_videos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'prompts_shown',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'prompts_answered',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'interventions_shown',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'interventions_effective',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'pre_sleep_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stats', 'binge_sessions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('intervention_events', 'user_left_youtube',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('intervention_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('idx_intervention_session', table_name='intervention_events')
    op.create_index(op.f('ix_intervention_events_session_id'), 'intervention_events', ['session_id'], unique=False)
    op.alter_column('mood_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_mood_reports_session_id'), 'mood_reports', ['session_id'], unique=False)
    op.alter_column('page_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('idx_page_session', table_name='page_events')
    op.create_index(op.f('ix_page_events_session_id'), 'page_events', ['session_id'], unique=False)
    op.alter_column('recommendation_events', 'was_autoplay_next',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('recommendation_events', 'autoplay_countdown_started',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('recommendation_events', 'autoplay_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('recommendation_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('idx_rec_session', table_name='recommendation_events')
    op.create_index(op.f('ix_recommendation_events_session_id'), 'recommendation_events', ['session_id'], unique=False)
    op.alter_column('scroll_events', 'visible_video_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scroll_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('idx_scroll_session', table_name='scroll_events')
    op.create_index(op.f('ix_scroll_events_session_id'), 'scroll_events', ['session_id'], unique=False)
    op.alter_column('thumbnail_events', 'hover_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('thumbnail_events', 'preview_played',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('thumbnail_events', 'preview_watch_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('thumbnail_events', 'clicked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('thumbnail_events', 'title_caps_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('thumbnail_events', 'title_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('thumbnail_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('idx_thumbnail_session', table_name='thumbnail_events')
    op.create_index(op.f('ix_thumbnail_events_session_id'), 'thumbnail_events', ['session_id'], unique=False)
    op.alter_column('video_sessions', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_sessions', 'watched_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_sessions', 'watched_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_sessions', 'is_short',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('video_sessions', 'playback_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('video_sessions', 'seek_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_sessions', 'pause_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_sessions', 'tab_switch_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('video_watch_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('idx_video_watch_session', table_name='video_watch_events')
    op.create_index(op.f('ix_video_watch_events_session_id'), 'video_watch_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_video_watch_events_watch_session_id'), 'video_watch_events', ['watch_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_watch_events_watch_session_id'), table_name='video_watch_events')
    op.drop_index(op.f('ix_video_watch_events_session_id'), table_name='video_watch_events')
    op.create_index('idx_video_watch_session', 'video_watch_events', ['watch_session_id'], unique=False)
    op.alter_column('video_watch_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('video_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('video_sessions', 'tab_switch_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_sessions', 'pause_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_sessions', 'seek_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_sessions', 'playback_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('video_sessions', 'is_short',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('video_sessions', 'watched_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_sessions', 'watched_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_sessions', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_thumbnail_events_session_id'), table_name='thumbnail_events')
    op.create_index('idx_thumbnail_session', 'thumbnail_events', ['session_id'], unique=False)
    op.alter_column('thumbnail_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('thumbnail_events', 'title_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('thumbnail_events', 'title_caps_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('thumbnail_events', 'clicked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('thumbnail_events', 'preview_watch_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('thumbnail_events', 'preview_played',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('thumbnail_events', 'hover_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_scroll_events_session_id'), table_name='scroll_events')
    op.create_index('idx_scroll_session', 'scroll_events', ['session_id'], unique=False)
    op.alter_column('scroll_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('scroll_events', 'visible_video_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_recommendation_events_session_id'), table_name='recommendation_events')
    op.create_index('idx_rec_session', 'recommendation_events', ['session_id'], unique=False)
    op.alter_column('recommendation_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('recommendation_events', 'autoplay_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('recommendation_events', 'autoplay_countdown_started',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('recommendation_events', 'was_autoplay_next',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_page_events_session_id'), table_name='page_events')
    op.create_index('idx_page_session', 'page_events', ['session_id'], unique=False)
    op.alter_column('page_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_mood_reports_session_id'), table_name='mood_reports')
    op.alter_column('mood_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_intervention_events_session_id'), table_name='intervention_events')
    op.create_index('idx_intervention_session', 'intervention_events', ['session_id'], unique=False)
    op.alter_column('intervention_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('intervention_events', 'user_left_youtube',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('daily_stats', 'binge_sessions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'pre_sleep_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'interventions_effective',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'interventions_shown',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'prompts_answered',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'prompts_shown',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'neutral_videos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'unproductive_videos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'productive_videos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'tab_switches',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'back_button_presses',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'page_reloads',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'thumbnails_clicked',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'thumbnails_hovered',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'avg_scroll_velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('daily_stats', 'total_scroll_pixels',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'autoplay_cancelled',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'autoplay_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'recommendation_clicks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'search_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'unique_channels',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'shorts_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'videos_abandoned',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'videos_completed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'video_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'avg_session_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'session_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'background_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'active_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_stats', 'total_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('browser_sessions', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('browser_sessions', sa.Column('active_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('browser_sessions', sa.Column('video_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('browser_sessions', 'neutral_videos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'unproductive_videos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'productive_videos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'time_on_shorts_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'time_on_search_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'time_on_watch_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'time_on_home_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'search_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'autoplay_cancelled',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'autoplay_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'recommendation_clicks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'back_button_presses',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'page_reloads',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'thumbnails_clicked',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'thumbnails_hovered',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'total_scroll_pixels',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'shorts_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'videos_started_not_finished',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'pages_visited',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'background_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'active_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('browser_sessions', 'total_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('browser_sessions', 'videos_watched')
    # ### end Alembic commands ###
